
# Jenkins service
app: 
  build: ./ # Use own Dockerfile to build custom Jenkins image
  ports:
    - ${PORT}:8080     # Expose port 8085
  volumes_from:     # Use the correct container defined below
    - data
  restart: always   # Assure to start the service when the host restart.

# Container for Jenkins data.
data:
  image: ubuntu    # Use the ubuntu Docker image to persist our jenkins data
  volumes:
    # Map the jenkins data to your persistent folder.
    # Set correct path to your local folder before `:`
    - ${DATA_PATH}:/var/jenkins_home:rw
    # Map local ssh folder to use ssh keys within jenkins
    - ${SSH_PATH}:/var/jenkins_home/.ssh:rw

    # TODO: Make this work below
    - /var/run/docker.sock:/tmp/sock
    - /var/run/docker.sock:/var/run/docker.sock
    - /usr/bin/docker:/usr/bin/docker